@urlDefecto = http://localhost:3000/apiV1

//--------------------------------------------

//usuario correcto
POST {{urlDefecto}}/auth
Content-Type: application/json

{
    "user":"admin",
    "contra":"123"
}

###
//usuario incorrecto
POST {{urlDefecto}}/auth
Content-Type: application/json

{
    "user":"a12312dmin",
    "contra":"12566d3"
}