@urlDefecto = http://localhost:3000/apiV1

//--------------------------------------------

//obtener todos los clientes
GET {{urlDefecto}}/clientes
Content-Type: application/json

###

//obtener un cliente por id
GET {{urlDefecto}}/clientes/7
Content-Type: application/json

###

//intentar obtener un cliente no válido
GET {{urlDefecto}}/clientes/15
Content-Type: application/json

###

//crear nuevo cliente
POST {{urlDefecto}}/clientes/
Content-Type: application/json

{
    "nombre":"y uno mas",
    "telefono":"11 3205 0648",
    "direccion":"juan cruz varela 14"
}

###

//crear nuevo cliente con string invalida
POST {{urlDefecto}}/clientes/
Content-Type: application/json

{
    "nombre":"cn",
    "telefono":"8",
    "direccion":"a14"
}


###

//modificar datos de un cliente por id
//aqui se puede agregar nombre, telefono o direccion
//para modificar los parámetros que se pasan en el body
//de la request
PUT {{urlDefecto}}/clientes/12
Content-Type: application/json

{
    "nombre": "nombre Modificado 2",
    "direccion":"calle Falsa 123"
}

###

//eliminar un cliente n este caso el id 12
DELETE {{urlDefecto}}/clientes/12
Content-Type: application/json


