@urlDefecto = http://localhost:3000

//-----------------------------------
//-----------------------------------

//solicitud de toda la lista de pedidos
GET {{urlDefecto}}/pedidos
Content-Type: application/json

###
//obtener un pedido por id
GET {{urlDefecto}}/pedidos/10
Content-Type: application/json

###
GET {{urlDefecto}}/pedidos/560
Content-Type: application/json

###
//creación de un pedido nuevo
POST {{urlDefecto}}/pedidos
Content-Type: application/json

{
    "cliente":"Cena Rusa S.r.l.",
    "fecha":"2026-09-04",
    "productos":[{
        "id": 301,
        "descripcion": "Sanghuches de miga triples variados x12",
        "costo": 18000,
        "cantidadAdquirida": 3
      }]
}

###
//modificacion total de un pedido
PUT {{urlDefecto}}/pedidos/22
Content-Type: application/json

{
    "fecha":"2026-09-05",
    "productos":[{
        "id":310,
        "descripcion":"Sanguches vegetarianos base queso x16",
        "costo":160000,
        "cantidadAdquirida":1
    }]
}

###
//modificacion parcial de un pedido
PUT {{urlDefecto}}/pedidos/5
Content-Type: application/json

{
   "estado":"cancelada"
}

###
PUT {{urlDefecto}}/pedidos/5
Content-Type: application/json

{
   "estado":"al toke roque"
}